"""Connect from Merlin to CSDS/SM

The methods `value_schema_to_sm` and `value_to_csds` perform identical decomposition in order to generate SM 
definitions and parse actual Merlin data, respectively.
"""
from typing import Tuple, List, Any
from arrow import Arrow
from copy import deepcopy

from fspa_scripts.ctu_merlin.data.merlin import *
from fspa_scripts.ctu_merlin.data.state_manager import *
from fspa_scripts.ctu_merlin.data.csds import *
from fspa_scripts.ctu_merlin.data.javadocs import JavadocState

STRUCT_DELIMITER = "--"


def value_schema_to_sm(identifier: str, schema: ValueSchema) -> Tuple[List[SMState], List[SMStateEnumeration], List[SMGroup]]:
    """Break down an arbitrarily complex Merlin state to a set of SM-compatible states

    Args:
        indentifier (str): name of the state
        schema (ValueSchema): Aerie value schema for the state

    Returns:
        states (List[SMState]): decomposed states in this state
        enumerations (List[SMStateEnumeration]): enumerations referenced in states
        groups (List[SMGroup]): groups generated by decomposition of combinatory states

    """
    # Initialize outputs
    states: List[SMState] = []
    enumerations: List[SMStateEnumeration] = []
    groups: List[SMGroup] = []

    if isinstance(schema, (BooleanSchema, DurationSchema, IntSchema, PathSchema, StringSchema, RealSchema, VariantSchema)):
        states.append(SMState(
            identifier=identifier,
            dataType="enum" if isinstance(
                schema, VariantSchema) else schema.get_type_string()
        ))

        # If this state is an enum (Aerie calls this "variant")
        if isinstance(schema, VariantSchema):

            # Add enumeration definition for this resource
            for variant in schema.variants:
                enumerations.append(SMStateEnumeration(
                    stateIdentifier=identifier,
                    label=variant["label"],
                    value=variant["key"]
                ))

    elif isinstance(schema, StructSchema):

        # Keep track of how this struct was broken down so we can define a group
        group_mappings = []
        sort_order_acc = 0

        # Decompose by looping over all items in the struct
        for item_name, item_schema in schema.items.items():

            # Struct item is parent resource name + item name, combined with STRUCT_DELIMITER
            new_state_identifier = f"{identifier}{STRUCT_DELIMITER}{item_name}"

            # Create and decompose the new resource
            new_states, new_enumerations, new_groups = value_schema_to_sm(
                new_state_identifier, item_schema
            )

            # Add the results of the recursive call to this call's accumulated states, enumerations, and groups
            states.extend(new_states)
            enumerations.extend(new_enumerations)
            groups.extend(new_groups)

            # Include all child states in a group
            for s in new_states:
                group_mappings.append(GroupMapping(
                    itemIdentifier=s.identifier,
                    itemType="State",
                    sortOrder=sort_order_acc
                ))
                sort_order_acc += 1

        # Create group of all children
        groups.append(SMGroup(
            identifier=identifier,
            groupMappings=group_mappings
        ))

    elif isinstance(schema, SeriesSchema):
        # TODO figure out how to handle these another time

        # For now, just create a state
        states.append(SMState(
            identifier=identifier,
            dataType="series"
        ))

    return states, enumerations, groups


def resource_to_csds(identifier: str, schema: ValueSchema, dynamics: Any, scet: Arrow) -> List[CSDSState]:
    """Parse a resource sample from Merlin to CSDS data

    Args:
        identifier (str): name of the resource
        schema (ValueSchema): describes the shape of the resource
        dynamics (Any): resource value
        scet (Arrow): absolute timestamp of the data

    Raises:
        ValueError: Failed to parse data according to value schema

    Returns:
        List[CSDSData]: CSDS data points generated from resource sample
    """
    # Initialize output
    csds_data: List[CSDSState] = []

    # Truncate subseconds to 3 decimal places
    scet_str = scet.strftime("%Y-%jT%H:%M:%S.%f")[:-3]

    if isinstance(schema, (BooleanSchema, DurationSchema, IntSchema, PathSchema, StringSchema, RealSchema, VariantSchema)):
        csds_data.append(CSDSState(
            # id=identifier,
            name=identifier,
            type="predict",
            value=float(dynamics),  # TODO only floats are allowed??
            scet=scet_str
        ))

    elif isinstance(schema, StructSchema):

        # Decompose by looping over all items in the struct
        for item_name, item_schema in schema.items.items():

            # Struct item is parent resource name + item name, combined with STRUCT_DELIMITER
            new_state_identifier = f"{identifier}{STRUCT_DELIMITER}{item_name}"

            # Create and decompose the new resource
            if dynamics is None:
                new_data = resource_to_csds(  # TODO update
                    new_state_identifier,
                    item_schema,
                    None,
                    scet
                )
            else:
                try:
                    new_data = resource_to_csds(  # TODO update
                        new_state_identifier,
                        item_schema,
                        dynamics[item_name],
                        scet
                    )
                except KeyError:
                    # TODO if the value is null, decompose the null state??
                    raise ValueError(
                        f"Value schema for {identifier} doesn't match data: {json.dumps(dynamics)}")

            # Add the results of the recursive call to this call's accumulated data
            csds_data.extend(new_data)

    elif isinstance(schema, SeriesSchema):
        # TODO figure out how to handle these another time

        # For now, just return the full JSON data
        csds_data.append(CSDSState(
            # id=identifier,
            name=identifier,
            type="predict",
            value=float(dynamics),  # TODO only floats are allowed??
            scet=scet_str
        ))

    return csds_data


def tag_csds_data(csds_data: List[CSDSState], collectionName: str, planId: str, runId: str) -> List[CSDSState]:
    csds_data = deepcopy(csds_data)
    for c in csds_data:
        c.collectionName = collectionName
        c.planId = planId
        c.runId = runId

    return csds_data


def javadoc_state_to_sm(javadoc_state: JavadocState, collection_id: str = None) -> Dict:
        sm_dict = {
            "identifier": javadoc_state.resource,
            "displayName": javadoc_state.resource,
            "dataType": "",
            "type": "predict",
            "units": javadoc_state.units,
            "source": "clipper-merlin",
            "subsystem": "",
            "channelId": "",
            "restricted": False,
            "description": javadoc_state.docs,
            "externalLink": "",
            "version": ""
        }
        if collection_id is not None:
            sm_dict["collection_id"] = collection_id

        return sm_dict
